export NUM_WORKERS=1
export DATA_DIR="/path/to/data"
export MODEL_NAME="black-forest-labs/FLUX.1-dev"
torchrun --nproc_per_node=$NUM_WORKERS cache_prompt_embeds.py \
    --data_root=$DATA_DIR \
    --batch_size=256 \
    --num_worker=$NUM_WORKERS \
    --pretrained_model_name_or_path=$MODEL_NAME \
    --mixed_precision='bf16' \
    --output_dir=$DATA_DIR \
    --column="prompt" \
    --max_sequence_length=512