[workspace]
channels = ["conda-forge"]
name = "URAE"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = "==1.26.4"
gpustat = ">=1.1.1,<2"
ncurses = ">=6.5,<7"

[pypi-dependencies]
torch = ">=2.1.0"
transformers = ">=4.57.1, <5"
diffusers = "==0.31.0"
sentencepiece = ">=0.2.1, <0.3"
accelerate = ">=1.11.0, <2"
opencv-python = ">=4.11.0.86, <5"
peft = ">=0.17.1, <0.18"
wandb = ">=0.22.3, <0.23"
jupyter = ">=1.1.1, <2"
patch-conv = { git = "https://github.com/mit-han-lab/patch_conv.git" }
